apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: workshop-quarkus-using_funqy_stateless_events
  title: Creating and Deploying a Serverless Function
  description: |
    Creating and Deploying your first Serverless Function
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - knative
    - serverless
    - kafka
    - quarkus
spec:
  type: module
  lifecycle: production
  owner: group:default/workshop-admins
  subcomponentOf: component:default/workshop-repository
