apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: workshop-quarkus-using_funqy_stateless_events
  title: Creating and Deploying a Serverless Function
  description: |
    Creating and Deploying your first Serverless Function
  annotations:
    backstage.io/techdocs-ref: dir:.
#   backstage.io/techdocs-ref: dir:https://<hosted-git-repo>     # use absolute path instead to consolidate techdocs among repo forks
  tags:
    - knative
    - serverless
    - kafka
    - quarkus
# links:
#   - url: https://<devspaces-url>/#<hosted-git-repo>
#     title: 🚀 Launch from Dev Spaces
#     icon: web
spec:
  type: module
  lifecycle: production
  owner: group:default/developers
  subcomponentOf: component:default/workshop-repository
